### ISSUE TITLE
Hosted version?

### ISSUE THREAD

**Issue by em0ney** [Leo-RASPAUD/leo-raspaud-resume-react#1]
Hi Leo,

Do you have a hosted version of this resume?  If so, can you provide a link to it?  If not, can you throw it up somewhere so I can take a peek?

**Comment by Leo-RASPAUD** [comment]
Hi Elliott, 
You can find the hosted version here : http://leo-raspaud.com/
But keep in mind that it was just a prototype that I did to try out React / Webpack. 
I'm currently working on another project in React/Redux/Node/Mongo but the code is on a private repository, I can give you the access if you give me your email address (you can contact me on leo.raspaud@gmail.com)
